ci: fix the CoCoKeyprovider image pushing logic
confidential-containers/guest-components pull request #673
Opened 2024-08-15 07:07 UTC by Xynnn007

As the original  repo is now archived, thus we havenot been able to publish the coco keyprovider image for a long time. This commit fixes this issue by changing the image repo.

Fixes #672

2024-08-15 07:18 UTC, mythi commented
Good timing with the PR as I was just looking at this file and noticed that is is missing `permissions`.

2024-08-15 12:23 UTC, fitzthum approved these changes
LGTM

2024-08-15 13:13 UTC, mythi requested changes
as part of fixing, add `permissions` to protect `GITHUB_TOKEN`

2024-08-16 15:07 UTC, mkulke approved these changes

2024-08-16 15:42 UTC, mythi approved these changes
LGTM

2024-08-17 03:15 UTC, merged